### ISSUE TITLE
creating rg_cities1000.csv

### ISSUE THREAD

**Issue by bdon** [thampiman/reverse-geocoder#1]
Hi, thanks for this library. Is the script to create the data file from a GeoNames dump available? The one committed seems to be missing some United States cities e.g. this lookup for a point in NYC:

    >>> reverse_geocoder.search([(40.729177554196376,-73.99343490600586)])
    [{'name': 'Byram', 'cc': 'US', 'lon': '-73.65374', 'admin1': 'Connecticut', 'admin2': 'Fairfield County', 'lat': '41.00426'}]

**Comment by thampiman** [comment]
Yes... it is in __init__.py. You can delete the rg_cities1000.csv file from the package folder and rerun the search. The latest dump from GeoNames is then used to recreate it. Let me know if that fixes the problem. Thanks!

**Comment by bdon** [comment]
Thanks, I see the script now. There seems to be about 6000 rows from the GeoNames file missing in the created file, trying to figure out why that is...

**Comment by bdon** [comment]
created patch [#4], closing
