### ISSUE TITLE
OverflowError: Python int too large to convert to C long

### ISSUE THREAD

**Issue by jzheng8** [thampiman/reverse-geocoder#16]
When I try to run the module in python 3.0 and up version, it will return an error:OverflowError: Python int too large to convert to C long. However, it should be fine when I run in python 2.0 and up 2.7 version.

**Comment by swails** [comment]
I just used this in Python 3.5 and didn't see this problem.  Can you post a minimal script that is giving rise to these errors?

**Comment by jzheng8** [comment]
![pi](https://cloud.githubusercontent.com/assets/16098658/14581423/2413ea8c-03bb-11e6-867f-866d01fcca2d.PNG)
Here your are.

**Comment by swails** [comment]
Oh, this is Windows...  works fine in Linux :).  You can replace line 8 in `reverse_geocoder/__init__.py` with a much smaller number:

```python
csv.field_size_limit(2**16)
```

That should work fine.

**Comment by jzheng8** [comment]
Oh thank you~.XD
