### ISSUE TITLE
Add requirements.txt

### ISSUE THREAD

**Issue by pyros2097** [thampiman/reverse-geocoder#18]
Please add a requirements.txt file containing the depencies used otherwise we have to manually add them in our requirements file and it becomes tedious.
```
scipy==0.17.1
numpy==1.11.0
```
Now I haz go to wait for 30 minutes for docker-compose to build my images again :+1: 
Thanks for the lib anways its really great and better than most revese geocoders I've seen

**Comment by pyros2097** [comment]
Did you update the version for pypi?

**Comment by thampiman** [comment]
Yes, please upgrade to the latest v1.4. I've included the numpy and scipy as dependencies in the setup.
