### ISSUE TITLE
It does not work for Python 3

### ISSUE THREAD

**Issue by stared** [thampiman/reverse-geocoder#2]
It does not work for Python 3, maybe only because of superficial syntax changes (e.g. brackets for `print`). 

E.g. 

    import reverse_geocoder as rg

raises

    File "/usr/local/lib/python3.4/site-packages/reverse_geocoder/__init__.py", line 88
      print 'Unable to parse coordinates:', coordinates
                                       ^
    SyntaxError: invalid syntax

**Comment by thampiman** [comment]
Yes I haven't tested it on Python 3. Will get on it... thanks!
