### ISSUE TITLE
Scipy requirement not documented.

### ISSUE THREAD

**Issue by rchrd2** [thampiman/reverse-geocoder#9]
```
   from scipy.spatial import cKDTree as KDTree
ImportError: No module named scipy.spatial
```
But even after installing scypi with pip, I still get the error.
```
pip install scipy
```
--Edit--
The pip install is failing on my vagrant. Investigating. 
`numpy.distutils.system_info.NotFoundError: no lapack/blas resources found`

In either case, it would be useful for the need for scipy to be documented in the README or included in the setup.py.

**Comment by thampiman** [comment]
Hi Richard -- It looks like you need to manually install gfortran, libopenblas and liblapack. Let me know if that works and I'll close this issue. I'll update the README to include the scipy & numpy requirements.

**Comment by rchrd2** [comment]
Yes. I had to install those libraries with apt-get prior to installing `numpy` and `scipy` with pip. Thanks.
